dadc/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/urls.py
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_label = "main"   

urlpatterns = [
    path('pdf/<int:number>/', views.req_file, name="pdf"),
    path('fb/<int:number>/', views.fb_page, name="fb"),
    path('pdf/', views.invoice, name="pdf2"),

    path("acces-non-autorise/", views.error403, name="error403"),
    path("ressource-introuvable/<message>/", views.error404, name="error404"),
    path("erreur/", views.error500, name="error500"),

    path("tableau-de-bord/", views.dashbord, name="dashbord"),
    path("profil/", views.profile, name="profile"),
    path("clients/", views.all_user, name="client"),
    path("agents-division-cadastre", views.all_guichet_user, name="guichet"),
    path("agents-bureau-de-bornage", views.all_bornage_user, name="b_bornage"),
    path("ordre-des-geometre", views.all_geometre_user, name="geometre"),
    path("agents-bureau-de-dessin", views.all_dessin_user, name="dessin"),
    path("agents-bureau-de-conservation", views.all_conservation_user, name="conservation"),
    path("changer-le-role", views.all_user, name="change_role"),

    path("register/", views.choose_register, name="register"),
    path("register/compte-particulier", views.person_register, name="person_register"),
    path("register/compte-entreprise", views.enterprise_register, name="enterprise_register"),
    path("login/", views.login_req, name="login"),
    path("logout/", views.logout_req, name="logout"),

    path("icons", views.icons, name="icons"),
    path("tables", views.tables, name="tables"),

    # Public
    path("", views.home, name="home"),
    path("journal-officiel", views.journal, name="journal"),
    path("travaux-de-bornage/", views.public_demarcations, name="bornage"),
    path("carte", views.carte, name="carte"),
    path("a-ventre", views.en_vente, name="en_vente"),

    # requisitions
    path("requisitions", views.requisitions, name="requisitions"),
    path("mes-requisitions", views.my_requisitions, name="my_requisitions"),
    path("requisitions/<int:number>/", views.single_requisition, name="single_requisition"),
    path("requisitions/<int:number>/facturation", views.payment, name="payment"),
    path("requisitions-response", views.state_requisition, name="state_requisition"),
    path("demander-une-requisition", views.add_requisition, name="add_requisition"),

    # plaintes
    path("plaintes", views.complaints, name="complaints"),
    path("mes-plaintes", views.my_complaints, name="my_complaints"),
    path("plaintes-response", views.state_complaint, name="state_complaint"),
    path("plaintes/<int:number>", views.add_complaint, name="add_complaint"),

    # Travaux de bornage
    path("travaux-de-bornage", views.demarcations, name="demarcations"),
    path("programmer-travaux-de-bornage", views.add_demarcation, name="add_demarcation"),

    # Rapport des ravaux de bornage
    path("rapports-travaux-de-bornage", views.reports, name="reports"),
    path("redaction-de-pv/<int:id>", views.add_report, name="add_report"),
    path("redaction-de-pv/<int:id>", views.reports, name="single_report"),
    path("redaction-de-pv/<int:number>/", views.single_requisition, name="add_plan"),


    # Titre foncier
    path("registre-foncier", views.deeds, name="deeds"),
    path("actifs-foncier", views.my_deeds, name="my_deeds"),
    path("registre-foncier/<int:number>", views.add_deed, name="add_deed"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'main.views.error404'

main/models.py
from datetime import datetime
from time import time
import django
from django.db import models
from django.contrib.auth.models import User, AbstractUser, BaseUserManager
from .choices import *
from .pays import *

class User(AbstractUser):
    id_document = models.FileField(upload_to='user/', null=True)

class Person(models.Model):
    gender = models.CharField(max_length=1, choices=GENDER)
    marital_status = models.CharField(max_length=1, choices=MARITAL_STATUS, default='1')
    partner_name = models.CharField(blank=True, max_length=200)
    profession = models.CharField(max_length=100, null=True)
    nationality = models.CharField(max_length=3, choices=PAYS, default='TG')
    birthday = models.DateField('birthday', default='2004-12-31')
    bornAt = models.CharField(max_length=100)
    address = models.CharField(max_length=200, default="")
    residence = models.CharField(blank=True, max_length=200, default='')
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    type = models.CharField(max_length=100, blank=True, default='CLIENT', choices=ROLE)
    phone = models.CharField(max_length=12, null=True)

    def __str__ (self):
        return self.user.username + "\t" + self.user.get_full_name() + "\t" + str(self.birthday) + "\t" + self.type


class Requisition(models.Model):
   
    UPLOAD = f'requisition/%Y/%m/%d/'

    NUMBER = int(time())
    number = models.BigIntegerField(default=NUMBER, primary_key=True)
    # Property info
    area_a = models.PositiveIntegerField()
    area_ca = models.PositiveIntegerField()
    quality = models.IntegerField(choices=QUALITY, default=1)
    type = models.IntegerField(choices=TYPE)
    info = models.CharField(max_length=100)
    quarter = models.CharField(max_length=100)
    real_name = models.CharField(max_length=100)
    prefecture = models.CharField(max_length=100)
    
    east = models.CharField(max_length=100)
    western = models.CharField(max_length=100)
    north = models.CharField(max_length=100)
    south = models.CharField(max_length=100)
    
    # Owners info
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author')
    co_owner = models.ManyToManyField(User, related_name='owners', blank=True)

    # Files and payment
    liquidation_receipt = models.FileField(upload_to=UPLOAD, null=True, blank=True)
    file = models.FileField(upload_to=UPLOAD, null=True, blank=True)
    land_receipt = models.FileField(upload_to=UPLOAD)
    authorization = models.FileField(upload_to=UPLOAD, null=True, blank=True)
    floor_plan = models.FileField(upload_to=UPLOAD)
    notarial_instrument = models.FileField(upload_to=UPLOAD, null=True, blank=True)
    pay = models.CharField(max_length=30, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True, blank=True)
    pay_date = models.DateTimeField(null=True, blank=True)

    def create_with_pk(self):
        instance = self.create()
        instance.save()     # probably this line is unneeded
        return instance


class State(models.Model):
    STATE = [('A', 'En cours'), ('P', 'En attente'), ('C', 'Rejetée'), ('T', 'Terminée')]

    requisition = models.ForeignKey(Requisition, on_delete=models.CASCADE)
    state = models.CharField(max_length=1, choices=STATE, null=True, blank=True)
    raison = models.CharField(max_length=100, default='Phase initiale')
    date = models.DateTimeField(auto_now_add=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='state_author', null=True)




class Complaint(models.Model):
    id = models.BigIntegerField(default=int(time()), primary_key=True)
    requisition = models.ForeignKey(Requisition, null=True, on_delete=models.CASCADE)

    object = models.CharField(max_length=100)
    message = models.TextField(max_length=1000)
    proof_file = models.FileField(upload_to='plaintes/%Y/%m/%d/')
    state = models.BooleanField(null=True)
    pub_date = models.DateTimeField(auto_now_add=True)
    state_date = models.DateTimeField(null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='complaint_author', null=True)

    state_author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='complaint_state_author', null=True)




class Demarcation(models.Model):
    requisition = models.ForeignKey(Requisition, on_delete=models.CASCADE)
    choosed_date = models.DateTimeField()
    date = models.DateTimeField(auto_now_add=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True)
    drawer = models.ForeignKey(User, on_delete=models.CASCADE, related_name='drawer', null=True)

    surveyor = models.ForeignKey(User, on_delete=models.CASCADE, related_name='surveyor', null=True)

    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='demarcation_author', null=True)




class Report(models.Model):
    demarcation = models.ForeignKey(Demarcation, on_delete=models.CASCADE)
    pv = models.TextField(max_length=1000)
    floor_plan = models.FileField(upload_to='plans/%Y/%m/%d/', null=True, blank=True)

    date = models.DateTimeField(auto_now_add=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True)
    state = models.BooleanField(null=True)



class Coordinate(models.Model):
    report = models.ForeignKey(Report, on_delete=models.CASCADE)
    x = models.FloatField(default=0)
    y = models.FloatField(default=0)



class landDeed(models.Model):
    number = models.BigIntegerField(default=int(time()))
    requisition = models.OneToOneField(Requisition, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='generated_by', null=True)




class Mutation(models.Model):
    landDeed = models.ForeignKey(landDeed, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True, blank=True)
    way = models.CharField(max_length=1, choices=WAY, default='H', blank=True)
    to = models.ForeignKey(User, on_delete=models.CASCADE, related_name='to', null=True)




class Sale(models.Model):
    landDeed = models.ForeignKey(landDeed, on_delete=models.CASCADE)
    price = models.PositiveIntegerField(default=0)
    date = models.DateTimeField(auto_now_add=True, blank=True)
    purchase = models.OneToOneField(Mutation, on_delete=models.CASCADE, null=True)

main/wkhtmltopdf/views.py
from __future__ import absolute_import

from django.http import HttpResponse
from django.template.response import TemplateResponse
from django.views.generic import TemplateView

from .utils import (content_disposition_filename, render_pdf_from_template)


class PDFResponse(HttpResponse):
    """HttpResponse that sets the headers for PDF output."""

    def __init__(self, content, status=200, content_type=None,
            filename=None, show_content_in_browser=None, *args, **kwargs):

        if content_type is None:
            content_type = 'application/pdf'

        super(PDFResponse, self).__init__(content=content,
                                          status=status,
                                          content_type=content_type)
        self.set_filename(filename, show_content_in_browser)

    def set_filename(self, filename, show_content_in_browser):
        self.filename = filename
        if filename:
            fileheader = 'attachment; filename={0}'
            if show_content_in_browser:
                fileheader = 'inline; filename={0}'

            filename = content_disposition_filename(filename)
            header_content = fileheader.format(filename)
            self['Content-Disposition'] = header_content
        else:
            del self['Content-Disposition']


class PDFTemplateResponse(TemplateResponse, PDFResponse):
    """Renders a Template into a PDF using wkhtmltopdf"""

    def __init__(self, request, template, context=None,
                 status=None, content_type=None, current_app=None,
                 filename=None, show_content_in_browser=None,
                 header_template=None, footer_template=None,
                 cmd_options=None, *args, **kwargs):
        cover_template = kwargs.pop('cover_template', None)

        super(PDFTemplateResponse, self).__init__(request=request,
                                                  template=template,
                                                  context=context,
                                                  status=status,
                                                  content_type=content_type,
                                                  *args, **kwargs)
        self.set_filename(filename, show_content_in_browser)

        self.header_template = header_template
        self.footer_template = footer_template
        self.cover_template = cover_template
        if cmd_options is None:
            cmd_options = {}
        self.cmd_options = cmd_options

    @property
    def rendered_content(self):
        """Returns the freshly rendered content for the template and context
        described by the PDFResponse.

        This *does not* set the final content of the response. To set the
        response content, you must either call render(), or set the
        content explicitly using the value of this property.
        """
        cmd_options = self.cmd_options.copy()
        return render_pdf_from_template(
            self.resolve_template(self.template_name),
            self.resolve_template(self.header_template),
            self.resolve_template(self.footer_template),
            context=self.resolve_context(self.context_data),
            request=self._request,
            cmd_options=cmd_options,
            cover_template=self.resolve_template(self.cover_template)

        )

class PDFTemplateView(TemplateView):
    """Class-based view for HTML templates rendered to PDF."""

    # Filename for downloaded PDF. If None, the response is inline.
    filename = 'rendered_pdf.pdf'

    # Send file as attachement. If True render content in the browser.
    show_content_in_browser = False

    # Filenames for the content, header, and footer templates.
    template_name = None
    header_template = None
    footer_template = None
    cover_template = None

    # TemplateResponse classes for PDF and HTML
    response_class = PDFTemplateResponse
    html_response_class = TemplateResponse

    # Command-line options to pass to wkhtmltopdf
    cmd_options = {
        # 'orientation': 'portrait',
        # 'collate': True,
        # 'quiet': None,
    }

    def __init__(self, *args, **kwargs):
        super(PDFTemplateView, self).__init__(*args, **kwargs)

        # Copy self.cmd_options to prevent clobbering the class-level object.
        self.cmd_options = self.cmd_options.copy()

    def get(self, request, *args, **kwargs):
        response_class = self.response_class
        try:
            if request.GET.get('as', '') == 'html':
                # Use the html_response_class if HTML was requested.
                self.response_class = self.html_response_class
            return super(PDFTemplateView, self).get(request,
                                                    *args, **kwargs)
        finally:
            # Remove self.response_class
            self.response_class = response_class

    def get_filename(self):
        return self.filename

    def get_cmd_options(self):
        return self.cmd_options

    def render_to_response(self, context, **response_kwargs):
        """
        Returns a PDF response with a template rendered with the given context.
        """
        filename = response_kwargs.pop('filename', None)
        cmd_options = response_kwargs.pop('cmd_options', None)

        if issubclass(self.response_class, PDFTemplateResponse):
            if filename is None:
                filename = self.get_filename()

            if cmd_options is None:
                cmd_options = self.get_cmd_options()

            return super(PDFTemplateView, self).render_to_response(
                context=context, filename=filename,
                show_content_in_browser=self.show_content_in_browser,
                header_template=self.header_template,
                footer_template=self.footer_template,
                cmd_options=cmd_options,
                cover_template=self.cover_template,
                **response_kwargs
            )
        else:
            return super(PDFTemplateView, self).render_to_response(
                context=context,
                **response_kwargs
            )

main/templates/requisition/fiche.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fiche de réquisition</title>
    <link rel="icon" type="image/x-icon"
        href="/home/lamiye/Documents/stage/IAI-L3/app/myapp/src/main/static/img/armoirie2.png" />
    <link href="/home/lamiye/Documents/stage/IAI-L3/app/myapp/src/main/static/css/styles.css" rel="stylesheet">
    <link href="/home/lamiye/Documents/stage/IAI-L3/app/myapp/src/main/static/css/bootstrap.min.css" rel="stylesheet">

</head>

<body>
    <div class="container d-flex justify-content-center py-5">
        <div class="card col-md-10 col border-0">
            <div class="card-body p-4">
            <div class="text-center">
                <div class="mb-4">
                    <p class=" ">
                        MINISTERE DE L'ECONOMIE ET DES FINANCES <br>
                        DIRECTION GENERALE DES IMPÔTS <br>
                        DIRECTION DES AFFAIRES DOMANIALES ET CADASTRALES (D.A.D.C)
                    </p>
                </div>
                <div class="border-bottom  border-secondary border-4 ">
                <P>
                        REPUBLIQUE TOGOLAISE <br> Travail - Liberté - Patrie
                    </P>
                </div>
            </div>
                <h1 class="text-center my-5">REQUISITION D'IMMATRICULATION</h1>
                <p class="mt-4 fs-6 lh-100">
                    L'(1)________{{requisition.author.person.get_gender_display}}
                    {{requisition.author.get_full_name}}__________________________________________________________<br>
                    Profession:__________{{requisition.author.person.profession}}________________________________, né à
                    ____________{{requisition.author.person.bornAt}}_____________<br>
                    le _____{{requisition.author.person.birthday}}_______, domicilé à
                    ________{{requisition.author.person.address}}________________________ <br>
                    Demeurant à ________{{requisition.author.person.residence}}_______________,
                    _______________{{requisition.author.person.get_marital_status_display}}__________________,<br>
                    soussigné ayant capacité suffisante aux fins des présentes, comme
                    __________{{requisition.get_quality_display}}____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________<br>
                    Et faisant, aux même fins élection de domicile à _____________{{requisition.quarter}}_____________
                    situé dans la préfecture de(s) {{requisition.prefecture}}
                    __________________________________________________________________________________________________________________________
                </p>
            </div>
        </div>
    </div>
</body>

</html>

main/templates/requisition/payment.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Facture</title>
  <link rel="icon" type="image/x-icon"
    href="/home/lamiye/Documents/stage/IAI-L3/app/myapp/src/main/static/img/armoirie2.png" />
  <link href="/home/lamiye/Documents/stage/IAI-L3/app/myapp/src/main/static/css/styles.css" rel="stylesheet">
  <link href="/home/lamiye/Documents/stage/IAI-L3/app/myapp/src/main/static/css/bootstrap.min.css" rel="stylesheet">

</head>

<body>
  <div class="container d-flex justify-content-center py-5">
    <div class="card col-md-10 col">
      <div class="card-body p-4">
        <div class="col d-flex justify-content-between">
          <div>
          <img src="/home/lamiye/Documents/stage/IAI-L3/app/myapp/src/main/templates/requisition/otr.png" alt="">
          </div>
          <div class="m-2 text-center">
            <h4>REPUBLIQUE TOGOLAISE</h4> <br> Travail - Liberté - Patrie
          </div>
        </div>
        <h1 class="text-center">FACTURE {{requisition.pay}}</h1>
        <p class="card-text">
        <ul class="list-unstyled">
          <li><u>Référence</u> : {{requisition.number}}</li>
          <li>
            <u>{% if requisition.author.person %}Nom{% else %}Raison sociale{% endif %}</u> :
            {{requisition.author.get_full_name}}
          </li>
          <li><u>Date de réquisition</u> : {{requisition.date}}</li>
          <li><u>Désignation</u> : Demande d'immatriculation au livre foncier de la République Togolaise</li>
          <li><u>Valeur vénale</u> : {{vv}}</li>
        </ul>
        </p>
        <div class="table-responsive">
          <table class="table table-striped">
            <thead>
              <tr>
                <th scope="">Droits</th>
                <th scope="">Taux</th>
                <th scope="">Montant</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>Droit d'enregistrement</td>
                <td>5%</td>
                <td>{{register}} F</td>
              </tr>
              <tr>
                <td>Taxes additionnelles</td>
                <td>1%</td>
                <td>{{taxe}} F</td>
              </tr>
              <tr>
                <td>Conservation foncière</td>
                <td>2%</td>
                <td>{{safe}} F</td>
              </tr>
              <tr>
                <td>Droit fixes</td>
                <td></td>
                <td>{{fixed}} F</td>
              </tr>
              <tr>
                <td>Frais d’insertion au JORT</td>
                <td></td>
                <td>{{jort}} F</td>
              </tr>
              <tr>
                <td>Frais de dépôtt</td>
                <td></td>
                <td>{{deposit}} F</td>
              </tr>
              <tr>
                <td>TOTAL À PAYER</td>
                <td></td>
                <td>{{register|add:taxe|add:safe|add:fixed|add:jort|add:deposit}} F</td>
              </tr>
            </tbody>
        </table>
        </div>
        {% comment %}
        <p class="">
        <form method="post" action="{% url 'payment' number=requisition.number %}">
          {% csrf_token %}
          <button class="btn btn-primary text-center" type="submit">
            <a href=""></a>PAYER
          </button>
        </form>
        </p>
        {% endcomment %}
        <p class="text-end m-2">
          FEDERER POUR BATIR
        </p>
      </div>
    </div>
  </div>
</body>

</html>

main/templates/requisition/read.html
{% extends template %}
{% block title %}Réquisitions{% endblock%}

{% block content %}
<div class="header bg-gradient-success pb-6">
  <div class="container-fluid">
    <div class="header-body">
      <div class="row align-items-center py-4">
        <div class="col-lg-6 col-7">
          <h6 class="h2 text-white d-inline-block mb-0">Réquisitions</h6>
          </ol>
          </nav>
        </div>
        <div class="col-lg-6 col-5 text-right">
          <a href="{% url 'add_requisition' %}" class="btn btn-sm btn-neutral">Nouvelle demande</a>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container-fluid mt--6 bg-white shadow">
  <div class="row">
    <div class="col">
      <div class="card">
        <!-- Card header -->
        <div class="card-header border-0">
          <h3 class="mb-0">LISTE DES REQUISITIONS</h3>
        </div>
        <div class="table-responsive text-darker">
          {% if requisitions %}
          <table class="display table text-darker" id="dataTable" style="width:100%">
            <thead class="thead-light">
              <tr>
                <td>#</td>
                {% if 'my_requisitions' not in segment %}
                <td>Requérant</td>
                {% endif %}
                <td>Prefecture</td>
                <td>Quartier</td>
                <td>Terrain</td>
                <td>Date</td>
                <td>Etat</td>
                <td>Progression</td>
                <td>&nbsp;</td>
              </tr>
            </thead>
            <tbody class="list">
              {% for requisition in requisitions %}
              <tr>

                <td>
                  <a href="{% url 'single_requisition' number=requisition.number %}">{{requisition.number}}</a>
                </td>
                {% if 'my_requisitions' not in segment %}
                <td>{{requisition.author.get_full_name}}</td>
                {% endif %}
                <td>{{requisition.prefecture}}</td>
                <td>{{requisition.quarter}}</td>
                <td>{{requisition.get_type_display}}</td>
                <td>{{requisition.date}}</td>
                {% with state=requisition.state_set.last %}
                <td>
                  <span class="badge badge-dot mr-4 text-darker">
                    {% if requisition.pay_date %}
                    <i class="{% if state.state == 'A' %} bg-success
                      {% elif state.state == 'P' %} bg-warning
                      {% elif state.state == 'C' %} bg-danger
                      {% else %} bg-default {% endif %}"></i>
                    <span class="">
                      {% if state %}
                      {{ state.get_state_display}}
                      {% else %} Sans réponse
                      {% endif %}
                    </span>
                  </span>
                  {% else %}
                  Payement Requis
                  {% endif %}
                </td>
                <td>
                  <div class="d-flex align-items-center">
                    <span class="completion mr-2">
                      {% if requisition.pay_date %}

                      {% if requisition.state_set.first.state == "A" %}

                      {% if requisition.demarcation_set.all%} 

                      {% if requisition.demarcation_set.last.report_set.all%} 
                      {% if requisition.state_set.last.state == "T"%} 
                      100%
                      {% else %} 75% {% endif %}

                      {% else %} 50% {% endif %}

                      {% else %} 25% {% endif %}

                      {% else %} 10% {% endif %}

                      {% else %} 1% {% endif %}
                    </span>
                  </div>
                </td>
                <td>
                  <div class="dropdown">
                    <a class="btn btn-sm btn-icon-only" href="#" role="button" data-toggle="dropdown"
                      aria-haspopup="true" aria-expanded="false">
                      <i class="fas fa-ellipsis-v"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                      <a class="dropdown-item"
                        href="{% url 'single_requisition' number=requisition.number %}">Consulter</a>
                      {% if not requisition.pay_date %}
                      <a class="dropdown-item" href="{% url 'payment' number=requisition.number %}">Payer</a>
                      {% else %}
                      {% if state.state is None %}
                      <form method="POST" action="{% url 'state_requisition' %}">
                        {% csrf_token %}
                        <input type="hidden" name="number" value="{{requisition.number}}">
                        <button type="submit" class="dropdown-item bg-success" value="A" name="state">Publier</button>
                        <button type="submit" class="dropdown-item bg-danger" value="C" name="state">Rejeter</button>
                      </form>
                      {% endif %}
                      {% endif %}
                    </div>
                  </div>
                </td>
                {% endwith %}
              </tr>
              {% endfor %}
            </tbody>
          </table>
          {% else %}
          <p class="text-center">Aucune réquisition n'a été fait</p>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>


{% endblock %}